openapi: 3.0.1
info:
  title: Simplic.OxS.CDN
  version: v1
servers:
- url: https://dev-oxs.simplic.io/cdn-api/v1
security:
- Bearer: []
paths:
  /CDN/get-file/{blobId}:
    get:
      parameters:
      - explode: false
        in: path
        name: blobId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                format: binary
                type: string
            application/json:
              schema:
                format: binary
                type: string
            text/json:
              schema:
                format: binary
                type: string
          description: Success
        "401":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - CDN
  /CDN/get-metadata/{blobId}:
    get:
      parameters:
      - explode: false
        in: path
        name: blobId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BlobMetadata'
            application/json:
              schema:
                $ref: '#/components/schemas/BlobMetadata'
            text/json:
              schema:
                $ref: '#/components/schemas/BlobMetadata'
          description: Success
        "401":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - CDN
  /CDN/upload-file:
    post:
      requestBody:
        content:
          multipart/form-data:
            encoding:
              files:
                style: form
            schema:
              $ref: '#/components/schemas/_CDN_upload_file_post_request'
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UploadFilesResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/UploadFilesResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/UploadFilesResponse'
          description: Success
        "401":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "400":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad Request
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - CDN
  /CDN/upload:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadBytesRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/UploadBytesRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UploadBytesRequest'
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UploadResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
          description: Success
        "401":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "400":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad Request
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - CDN
  /CDN/{blobId}:
    delete:
      parameters:
      - explode: false
        in: path
        name: blobId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BlobMetadata'
            application/json:
              schema:
                $ref: '#/components/schemas/BlobMetadata'
            text/json:
              schema:
                $ref: '#/components/schemas/BlobMetadata'
          description: Success
        "401":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "404":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - CDN
components:
  schemas:
    BlobMetadata:
      additionalProperties: false
      example:
        fileName: fileName
        size: 0
        id: id
        mimeType: mimeType
        lastModified: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          nullable: true
          type: string
        fileName:
          nullable: true
          type: string
        mimeType:
          nullable: true
          type: string
        size:
          format: int64
          type: integer
        lastModified:
          format: date-time
          type: string
      type: object
    ProblemDetails:
      additionalProperties: {}
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
      type: object
    UploadBytesRequest:
      additionalProperties: false
      example:
        fileName: fileName
        data: data
        contentType: contentType
      properties:
        data:
          format: byte
          type: string
        fileName:
          minLength: 1
          type: string
        contentType:
          nullable: true
          type: string
      required:
      - data
      - fileName
      type: object
    UploadFilesResponse:
      additionalProperties: false
      example:
        uploadedFiles:
        - size: 0
          timeOfUpload: 2000-01-23T04:56:07.000+00:00
          name: name
          blobId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - size: 0
          timeOfUpload: 2000-01-23T04:56:07.000+00:00
          name: name
          blobId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        uploadedFiles:
          items:
            $ref: '#/components/schemas/UploadResponse'
          nullable: true
          type: array
      type: object
    UploadResponse:
      additionalProperties: false
      example:
        size: 0
        timeOfUpload: 2000-01-23T04:56:07.000+00:00
        name: name
        blobId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        name:
          nullable: true
          type: string
        size:
          format: int64
          type: integer
        timeOfUpload:
          format: date-time
          type: string
        blobId:
          format: uuid
          type: string
      type: object
    _CDN_upload_file_post_request:
      properties:
        files:
          items:
            format: binary
            type: string
          type: array
      type: object
  securitySchemes:
    Bearer:
      description: "JWT Authorization header using the Bearer scheme. \r\n\r\n Enter\
        \ 'Bearer' [space] and then your token in the text input below.\r\n\r\nExample:\
        \ \"Bearer 12345abcdef\""
      in: header
      name: Authorization
      type: apiKey

